<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions name="NewSalesOrderPartyATGSOAP11Processor" targetNamespace="http://xmlns.netshoes.com/components/v1" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://xmlns.netshoes.com/components/v1" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:import location="v1.xsd" namespace="http://xmlns.netshoes.com/components/v1"/>
  <WL5G3N0:types>
    <xsd:schema targetNamespace="http://xmlns.netshoes.com/components/v1" xmlns:nscmpnt1="http://xmlns.netshoes.com/components/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:element name="pollNewSalesOrderRequest">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="CodigoCatalogo" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="pollNewSalesOrderResponse" type="nscmpnt1:pollNewSalesOrderResponse"/>
      <xsd:complexType name="pollNewSalesOrderResponse">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" ref="IdUsuarios"/>
          <xsd:element maxOccurs="1" minOccurs="0" ref="Result"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="pollNewSalesOrderRequest">
    <WL5G3N0:part element="WL5G3N1:pollNewSalesOrderRequest" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="pollNewSalesOrderResponse">
    <WL5G3N0:part element="WL5G3N1:pollNewSalesOrderResponse" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="NewSalesOrderPartyATGSOAP11Processor">
    <WL5G3N0:operation name="pollNewSalesOrder">
      <WL5G3N0:input message="WL5G3N1:pollNewSalesOrderRequest"/>
      <WL5G3N0:output message="WL5G3N1:pollNewSalesOrderResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="NewSalesOrderPartyATGSOAP11ProcessorSOAP" type="WL5G3N1:NewSalesOrderPartyATGSOAP11Processor">
    <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="pollNewSalesOrder">
      <WL5G3N2:operation soapAction="http://xmlns.netshoes.com/components/v1/NewSalesOrderPartyATGSOAP11Processor/pollNewSalesOrder"/>
      <WL5G3N0:input>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="NewSalesOrderPartyATGSOAP11ProcessorSOAPQSService">
    <WL5G3N0:port binding="WL5G3N1:NewSalesOrderPartyATGSOAP11ProcessorSOAP" name="NewSalesOrderPartyATGSOAP11ProcessorSOAPQSPort">
      <WL5G3N2:address location="http://servicebus-qa.ns2online.com.br:80/components/NewSalesOrderATGSOAP11Processor/v1"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>